/**
 * Seed data constants — usável programaticamente (API routes, scripts, etc.)
 * Não depende de `process.exit` ou ambiente de CLI.
 */

export const newsCategories = [
  { name: "Saneamento Básico", slug: "saneamento-basico", color: "#0077B6", description: "Notícias gerais sobre saneamento básico no Brasil", icon: "droplets" },
  { name: "Tratamento de Água", slug: "tratamento-agua", color: "#00B4D8", description: "Tecnologias e processos de tratamento de água", icon: "glass-water" },
  { name: "Tratamento de Esgoto", slug: "tratamento-esgoto", color: "#48CAE4", description: "Sistemas e tecnologias de tratamento de esgoto", icon: "waves" },
  { name: "Regulação e Política", slug: "regulacao-politica", color: "#90E0EF", description: "Marco regulatório, leis e políticas públicas", icon: "landmark" },
  { name: "Tecnologia e Inovação", slug: "tecnologia-inovacao", color: "#2E7D32", description: "Inovações tecnológicas aplicadas ao setor", icon: "cpu" },
  { name: "Engenharia", slug: "engenharia", color: "#F9A825", description: "Engenharia sanitária, civil e ambiental", icon: "hard-hat" },
  { name: "Meio Ambiente", slug: "meio-ambiente", color: "#43A047", description: "Sustentabilidade e impacto ambiental", icon: "leaf" },
  { name: "Mercado e Negócios", slug: "mercado-negocios", color: "#EF6C00", description: "Concessões, privatizações e mercado do setor", icon: "trending-up" },
  { name: "Infraestrutura", slug: "infraestrutura", color: "#6D4C41", description: "Obras, projetos e infraestrutura de saneamento", icon: "building" },
];

export const newsSources = [
  // ── RSS funcionando (verificado) ────────────────────────────────────────────
  { name: "Instituto Trata Brasil", slug: "trata-brasil", url: "https://tratabrasil.org.br", feedUrl: "https://tratabrasil.org.br/feed/", fetchMethod: "RSS", isActive: true, fetchConfig: null },
  { name: "Instituto Água e Saneamento", slug: "ias", url: "https://www.aguaesaneamento.org.br", feedUrl: "https://www.aguaesaneamento.org.br/feed/", fetchMethod: "RSS", isActive: true, fetchConfig: null },
  { name: "ABES", slug: "abes", url: "https://abes.org.br", feedUrl: "https://abes.org.br/feed/", fetchMethod: "RSS", isActive: true, fetchConfig: null },
  { name: "Saneamento Hoje", slug: "saneamento-hoje", url: "https://saneamentohoje.com.br", feedUrl: "https://saneamentohoje.com.br/feed/", fetchMethod: "RSS", isActive: true, fetchConfig: null },
  { name: "AESBE", slug: "aesbe", url: "https://aesbe.org.br", feedUrl: "https://aesbe.org.br/feed/", fetchMethod: "RSS", isActive: true, fetchConfig: null },
  { name: "SINDAE", slug: "sindae", url: "https://sindae.org.br", feedUrl: "https://sindae.org.br/feed/", fetchMethod: "RSS", isActive: true, fetchConfig: null },

  // ── RSS inativo (feed inválido ou site fora do ar) ───────────────────────
  { name: "Saneamento Básico", slug: "saneamento-basico", url: "https://saneamentobasico.com.br", feedUrl: "https://saneamentobasico.com.br/feed/", fetchMethod: "RSS", isActive: false, fetchConfig: null },
  { name: "Engenharia 360", slug: "engenharia360", url: "https://engenharia360.com", feedUrl: "https://engenharia360.com/feed/", fetchMethod: "RSS", isActive: false, fetchConfig: null },
  { name: "Inovação Tecnológica", slug: "inovacao-tecnologica", url: "https://www.inovacaotecnologica.com.br", feedUrl: "https://www.inovacaotecnologica.com.br/boletim/feed.rss", fetchMethod: "RSS", isActive: false, fetchConfig: null },
  { name: "Revista Hydro", slug: "revista-hydro", url: "https://www.revistashydro.com.br", feedUrl: "https://www.revistashydro.com.br/feed/", fetchMethod: "RSS", isActive: false, fetchConfig: null },
  { name: "Portal Digital Water", slug: "digital-water", url: "https://portaldigitalwater.com", feedUrl: "https://portaldigitalwater.com/feed/", fetchMethod: "RSS", isActive: false, fetchConfig: null },
  { name: "ABCON", slug: "abcon", url: "https://www.abcon.com.br", feedUrl: "https://www.abcon.com.br/feed/", fetchMethod: "RSS", isActive: false, fetchConfig: null },
  { name: "ASSEMAE", slug: "assemae", url: "https://assemae.org.br", feedUrl: "https://assemae.org.br/feed/", fetchMethod: "RSS", isActive: false, fetchConfig: null },
  { name: "Canal Saneamento", slug: "canal-saneamento", url: "https://canalsaneamento.com.br", feedUrl: "https://canalsaneamento.com.br/feed/", fetchMethod: "RSS", isActive: false, fetchConfig: null },
  { name: "Tratamento de Água", slug: "tratamento-de-agua", url: "https://tratamentodeagua.com.br", feedUrl: "https://tratamentodeagua.com.br/feed/", fetchMethod: "RSS", isActive: false, fetchConfig: null },
  { name: "Agência Brasil — Meio Ambiente", slug: "agencia-brasil-meio-ambiente", url: "https://agenciabrasil.ebc.com.br", feedUrl: "https://agenciabrasil.ebc.com.br/medio-ambiente/feed/atom", fetchMethod: "RSS", isActive: false, fetchConfig: null },
  { name: "Sanear Magazine", slug: "sanear-magazine", url: "https://revistasanear.com.br", feedUrl: "https://revistasanear.com.br/feed/", fetchMethod: "RSS", isActive: false, fetchConfig: null },

  // ── HTML Scrape ativo ────────────────────────────────────────────────────
  { name: "Caesb", slug: "caesb", url: "https://www.caesb.df.gov.br", scrapeUrl: "https://www.caesb.df.gov.br/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .tileItem, .summary", titleSelector: "h2 a, h3 a, .tileHeadline a", summarySelector: ".tileBody, p", imageSelector: "img", linkSelector: "a.summary-url, h2 a" }) },
  { name: "ANA - Agência Nacional de Águas", slug: "ana", url: "https://www.gov.br/ana", scrapeUrl: "https://www.gov.br/ana/pt-br/assuntos/noticias-e-eventos/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .tileItem, .summary", titleSelector: "h2 a, h3 a, .tileHeadline a", summarySelector: ".tileBody, .summary-text, p", imageSelector: "img.thumb", linkSelector: "a.summary-url, h2 a" }) },
  { name: "Ministério das Cidades", slug: "mcidades", url: "https://www.gov.br/cidades", scrapeUrl: "https://www.gov.br/cidades/pt-br/assuntos/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .tileItem, .summary", titleSelector: "h2 a, h3 a, .tileHeadline a", summarySelector: ".tileBody, .summary-text, p", imageSelector: "img.thumb", linkSelector: "a.summary-url, h2 a" }) },
  { name: "GovTech Saneamento", slug: "govtech-saneamento", url: "https://www.gov.br/sesan", scrapeUrl: "https://www.gov.br/sesan/pt-br/assuntos/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: ".tileItem, article, .summary", titleSelector: ".tileHeadline a, h2 a", summarySelector: ".tileBody, p", imageSelector: "img", linkSelector: "a.summary-url, .tileHeadline a" }) },
  { name: "Aegea", slug: "aegea", url: "https://www.aegea.com.br", scrapeUrl: "https://www.aegea.com.br/noticias/", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .noticia-card, .post-item", titleSelector: "h2 a, h3 a, .titulo a", summarySelector: ".resumo, .excerpt, p", imageSelector: "img", linkSelector: "h2 a, h3 a, a.read-more" }) },
  { name: "Sabesp", slug: "sabesp", url: "https://www.sabesp.com.br", scrapeUrl: "https://www.sabesp.com.br/o-que-fazemos/noticias-e-comunicados", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .noticia-item, li.item", titleSelector: "h2 a, h3 a, .titulo", summarySelector: ".resumo, p", imageSelector: "img", linkSelector: "h2 a, h3 a, a" }) },
  { name: "Copasa", slug: "copasa", url: "https://www.copasa.com.br", scrapeUrl: "https://www.copasa.com.br/wps/portal/internet/imprensa/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .noticia-item, .ibm-card", titleSelector: "h2 a, h3 a, .ibm-card__title a", summarySelector: ".resumo, p", imageSelector: "img", linkSelector: "a.ibm-forward-link, h2 a" }) },
  { name: "Sanepar", slug: "sanepar", url: "https://site.sanepar.com.br", scrapeUrl: "https://site.sanepar.com.br/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .views-row, .card", titleSelector: "h2 a, h3 a, .card-title a", summarySelector: ".views-field-body, .card-text", imageSelector: "img", linkSelector: "h2 a, .card-title a" }) },
  { name: "Iguá Saneamento", slug: "igua", url: "https://www.igua.com.br", scrapeUrl: "https://www.igua.com.br/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .noticia-item, .card", titleSelector: "h2 a, h3 a, .card-title a", summarySelector: ".resumo, .excerpt, p", imageSelector: "img", linkSelector: "h2 a, h3 a, a" }) },
  { name: "FUNASA", slug: "funasa", url: "https://www.funasa.gov.br", scrapeUrl: "https://www.funasa.gov.br/web/guest/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .portlet-content li", titleSelector: "h3 a, h4 a, .asset-title a", summarySelector: ".asset-summary p, p", imageSelector: "img", linkSelector: "h3 a, .asset-title a" }) },
  { name: "BRK Ambiental", slug: "brk-ambiental", url: "https://www.brkambiental.com.br", scrapeUrl: "https://www.brkambiental.com.br/sala-de-imprensa", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .noticia-item, .card", titleSelector: "h2 a, h3 a, .card-title a", summarySelector: ".resumo, .excerpt, p", imageSelector: "img", linkSelector: "h2 a, h3 a, a" }) },
  { name: "Embasa", slug: "embasa", url: "https://www.embasa.ba.gov.br", scrapeUrl: "https://www.embasa.ba.gov.br/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .noticia-item, .item", titleSelector: "h2 a, h3 a, .titulo a", summarySelector: ".resumo, p", imageSelector: "img", linkSelector: "h2 a, h3 a" }) },
  { name: "CAGECE", slug: "cagece", url: "https://www.cagece.com.br", scrapeUrl: "https://www.cagece.com.br/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .noticia-card, .post", titleSelector: "h2 a, h3 a", summarySelector: ".excerpt, p", imageSelector: "img", linkSelector: "h2 a, a.read-more" }) },
  { name: "CEDAE", slug: "cedae", url: "https://www.cedae.com.br", scrapeUrl: "https://www.cedae.com.br/imprensa/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .noticia-item, .card, li.item", titleSelector: "h2 a, h3 a, .titulo a, .card-title a", summarySelector: ".resumo, .excerpt, p", imageSelector: "img", linkSelector: "h2 a, h3 a, a.leia-mais" }) },
  { name: "Corsan", slug: "corsan", url: "https://www.corsan.com.br", scrapeUrl: "https://www.corsan.com.br/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .noticia-item, .card, .views-row", titleSelector: "h2 a, h3 a, .card-title a", summarySelector: ".views-field-body, .card-text, p", imageSelector: "img", linkSelector: "h2 a, h3 a, a.btn" }) },
  { name: "Casan", slug: "casan", url: "https://www.casan.com.br", scrapeUrl: "https://www.casan.com.br/menu-conteudo/index/url/noticias", fetchMethod: "HTML_SCRAPE", isActive: true, fetchConfig: JSON.stringify({ articleListSelector: "article, .noticia-item, .card", titleSelector: "h2 a, h3 a, .titulo a", summarySelector: ".resumo, p", imageSelector: "img", linkSelector: "h2 a, h3 a" }) },
];

export const licitacaoSources = [
  { name: "PNCP", slug: "pncp", baseUrl: "https://pncp.gov.br/api/consulta", fetchMethod: "PNCP_API", fetchConfig: JSON.stringify({ searchEndpoint: "/v1/contratacoes/publicacao", defaultPageSize: 50, keywords: ["saneamento", "água", "esgoto", "tratamento", "abastecimento", "drenagem", "resíduos sólidos"] }), isActive: true },
  { name: "Compras.gov.br", slug: "compras-gov", baseUrl: "https://api.compras.dados.gov.br", fetchMethod: "COMPRAS_GOV_API", fetchConfig: JSON.stringify({ format: "json" }), isActive: true },
  { name: "BEC-SP", slug: "bec-sp", baseUrl: "https://www.bec.sp.gov.br", fetchMethod: "BEC_SP_SCRAPE", fetchConfig: JSON.stringify({ keywords: ["saneamento", "água", "agua", "esgoto", "drenagem", "resíduos", "residuos", "tubulação", "bomba"] }), isActive: true },
  { name: "Licitacoes-e (Banco do Brasil)", slug: "licitacoes-e", baseUrl: "https://www.licitacoes-e.com.br", fetchMethod: "HTML_SCRAPE", fetchConfig: JSON.stringify({ articleListSelector: ".licitacao-item", titleSelector: ".descricao", linkSelector: "a" }), isActive: false },
  // Portais estaduais de compras
  { name: "ComprasSP (BEC-SP)", slug: "compras-sp", baseUrl: "https://www.bec.sp.gov.br/Default.aspx", fetchMethod: "HTML_SCRAPE", fetchConfig: JSON.stringify({ keywords: ["saneamento","água","esgoto","drenagem","resíduos","tubulação","bomba","estação"] }), isActive: false },
  { name: "ComprasMG", slug: "compras-mg", baseUrl: "https://www.compras.mg.gov.br", fetchMethod: "HTML_SCRAPE", fetchConfig: JSON.stringify({ keywords: ["saneamento","água","esgoto"] }), isActive: false },
  { name: "ComprasRJ", slug: "compras-rj", baseUrl: "https://riocompras.rio.rj.gov.br", fetchMethod: "HTML_SCRAPE", fetchConfig: JSON.stringify({ keywords: ["saneamento","água","esgoto"] }), isActive: false },
  // PNCP específico para cada tipo de objeto de saneamento
  { name: "PNCP — Obras Hídricas", slug: "pncp-obras-hidricas", baseUrl: "https://pncp.gov.br/api/consulta", fetchMethod: "PNCP_API", fetchConfig: JSON.stringify({ searchEndpoint: "/v1/contratacoes/publicacao", keywords: ["obras hídricas","adutora","ETA","ETE","elevatória","reservatório","rede de distribuição","rede coletora","interceptor de esgoto"] }), isActive: true },
  // Portais agregadores de licitações
  { name: "Portal de Compras Públicas", slug: "portal-compras-publicas", baseUrl: "https://www.portaldecompraspublicas.com.br", fetchMethod: "HTML_SCRAPE", fetchConfig: JSON.stringify({ keywords: ["saneamento","água","esgoto","drenagem","resíduos","tubulação","bomba","ETA","ETE"] }), isActive: false },
  { name: "BLL Compras", slug: "bll-compras", baseUrl: "https://bllcompras.com", fetchMethod: "HTML_SCRAPE", fetchConfig: JSON.stringify({ keywords: ["saneamento","água","esgoto","drenagem","resíduos","tubulação"] }), isActive: false },
];

export const licitacaoCategories = [
  { name: "Saneamento e Água", slug: "saneamento-agua", color: "#0077B6", description: "Sistemas de abastecimento de água e esgotamento sanitário", keywords: JSON.stringify(["saneamento", "água", "esgoto", "abastecimento", "eta", "ete"]) },
  { name: "Engenharia Civil", slug: "engenharia-civil", color: "#F9A825", description: "Obras de engenharia e construção civil", keywords: JSON.stringify(["engenharia", "obra", "construção", "edificação", "pavimentação"]) },
  { name: "Resíduos Sólidos", slug: "residuos-solidos", color: "#43A047", description: "Coleta, tratamento e disposição de resíduos", keywords: JSON.stringify(["resíduo", "lixo", "coleta", "reciclagem", "aterro"]) },
  { name: "Drenagem Urbana", slug: "drenagem-urbana", color: "#00B4D8", description: "Sistemas de drenagem e controle de enchentes", keywords: JSON.stringify(["drenagem", "enchente", "alagamento", "bueiro", "galeria"]) },
  { name: "Equipamentos", slug: "equipamentos", color: "#6D4C41", description: "Aquisição de equipamentos e materiais", keywords: JSON.stringify(["equipamento", "bomba", "motor", "tubulação", "válvula", "medidor"]) },
  { name: "Consultoria", slug: "consultoria", color: "#8B5CF6", description: "Serviços de consultoria e projetos", keywords: JSON.stringify(["consultoria", "projeto", "estudo", "diagnóstico", "plano"]) },
  { name: "Tecnologia da Informação", slug: "ti", color: "#2E7D32", description: "Sistemas e serviços de TI", keywords: JSON.stringify(["software", "sistema", "tecnologia", "informatica", "digital"]) },
  { name: "Outros", slug: "outros", color: "#6B6B73", description: "Outras categorias de licitação", keywords: null },
];

export const legislationCategories = [
  { name: "Saneamento", slug: "saneamento-leg", color: "#0077B6", icon: "droplets" },
  { name: "Licitações", slug: "licitacoes-leg", color: "#F9A825", icon: "gavel" },
  { name: "Segurança do Trabalho", slug: "seguranca", color: "#EF4444", icon: "shield" },
  { name: "Normas Técnicas", slug: "normas-tecnicas", color: "#8B5CF6", icon: "file-text" },
  { name: "Regulação", slug: "regulacao", color: "#22C55E", icon: "landmark" },
  { name: "Recursos Hídricos", slug: "recursos-hidricos", color: "#00B4D8", icon: "waves" },
  { name: "Meio Ambiente", slug: "meio-ambiente-leg", color: "#43A047", icon: "leaf" },
  { name: "Saúde Pública", slug: "saude-publica", color: "#EF6C00", icon: "heart-pulse" },
  { name: "Infraestrutura e Concessões", slug: "infraestrutura-concessoes", color: "#6D4C41", icon: "building" },
];

export const legislationItems = [
  { slug: "lei-14026-2020", title: "Lei n. 14.026/2020 — Novo Marco Legal do Saneamento Básico", shortTitle: "Marco Legal do Saneamento", description: "Atualiza o marco legal do saneamento básico, estabelecendo metas de universalização até 2033 (99% água e 90% esgoto). Estimula a regionalização e participação do setor privado.", type: "LEI", number: "14.026/2020", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2020/lei/L14026.htm", publishedAt: new Date("2020-07-15"), effectiveAt: new Date("2020-07-16"), legCategorySlug: "saneamento-leg" },
  { slug: "lei-14133-2021", title: "Lei n. 14.133/2021 — Nova Lei de Licitações e Contratos", shortTitle: "Nova Lei de Licitações", description: "Substitui a Lei 8.666/1993. Estabelece normas gerais de licitação e contratação para a administração pública.", type: "LEI", number: "14.133/2021", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/L14133.htm", publishedAt: new Date("2021-04-01"), effectiveAt: new Date("2021-04-01"), legCategorySlug: "licitacoes-leg" },
  { slug: "decreto-12303-2024", title: "Decreto n. 12.303/2024 — Programa de Governança de Estatais", shortTitle: "Decreto 12.303/2024", description: "Institui o Programa de Governança e Modernização das Empresas Estatais.", type: "DECRETO", number: "12.303/2024", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/decreto/D12303.htm", publishedAt: new Date("2024-11-28"), effectiveAt: new Date("2024-11-28"), legCategorySlug: "saneamento-leg" },
  { slug: "nr-18", title: "NR-18 — Segurança e Saúde no Trabalho na Construção", shortTitle: "NR-18", description: "Estabelece diretrizes de segurança nos processos da indústria da construção.", type: "NORMA_REGULAMENTADORA", number: "18", issuingBody: "Ministério do Trabalho e Emprego", documentUrl: "https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/normas-regulamentadoras/nr-18", publishedAt: new Date("1978-06-08"), effectiveAt: new Date("2022-01-01"), legCategorySlug: "seguranca" },
  { slug: "nbr-12211-2024", title: "NBR 12.211/2024 — Estudos de Concepção de Sistemas de Abastecimento de Água", shortTitle: "NBR 12.211", description: "Define condições para elaboração de estudos de concepção de sistemas públicos de abastecimento de água.", type: "NBR", number: "12.211/2024", issuingBody: "ABNT", documentUrl: "https://www.abntcatalogo.com.br", publishedAt: new Date("2024-01-15"), legCategorySlug: "normas-tecnicas" },
  { slug: "resolucao-ana-211-2024", title: "Resolução ANA n. 211/2024 — Indicadores Operacionais de Água e Esgoto", shortTitle: "Resolução ANA 211", description: "Estabelece indicadores operacionais de água e esgoto para prestadores de serviços de saneamento.", type: "RESOLUCAO", number: "211/2024", issuingBody: "ANA", documentUrl: "https://www.gov.br/ana", publishedAt: new Date("2024-06-15"), legCategorySlug: "regulacao" },
  { slug: "resolucao-ana-122-2023", title: "Resolução ANA n. 122/2023 — Norma de Referência de Regulação Tarifária", shortTitle: "Resolução ANA 122", description: "Estabelece norma de referência para regulação tarifária dos serviços públicos de saneamento básico.", type: "RESOLUCAO", number: "122/2023", issuingBody: "ANA", documentUrl: "https://www.gov.br/ana", publishedAt: new Date("2023-12-01"), legCategorySlug: "regulacao" },

  // ── Saneamento Básico (lei original + regulamentos) ──────────────────────
  { slug: "lei-11445-2007", title: "Lei n. 11.445/2007 — Lei Nacional de Saneamento Básico", shortTitle: "Lei de Saneamento 11.445", description: "Estabelece as diretrizes nacionais para o saneamento básico, definindo os princípios fundamentais, a prestação de serviços públicos de saneamento, o planejamento, a regulação e fiscalização. Base legal predecessor ao Marco Legal de 2020.", type: "LEI", number: "11.445/2007", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2007/lei/l11445.htm", publishedAt: new Date("2007-01-05"), effectiveAt: new Date("2007-01-05"), legCategorySlug: "saneamento-leg" },
  { slug: "decreto-7217-2010", title: "Decreto n. 7.217/2010 — Regulamento da Lei de Saneamento Básico", shortTitle: "Decreto 7.217/2010", description: "Regulamenta a Lei 11.445/2007, estabelecendo normas para execução das políticas nacionais de saneamento básico, incluindo planos de saneamento, contratos de prestação de serviços, metas e indicadores.", type: "DECRETO", number: "7.217/2010", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2010/decreto/d7217.htm", publishedAt: new Date("2010-06-21"), effectiveAt: new Date("2010-06-21"), legCategorySlug: "saneamento-leg" },
  { slug: "resolucao-ana-148-2023", title: "Resolução ANA n. 148/2023 — Regularização Fundiária", shortTitle: "Resolução ANA 148", description: "Estabelece norma de referência sobre regularização fundiária em áreas de serviço de saneamento básico, balizando os reguladores estaduais e municipais.", type: "RESOLUCAO", number: "148/2023", issuingBody: "ANA", documentUrl: "https://www.gov.br/ana", publishedAt: new Date("2023-09-01"), legCategorySlug: "saneamento-leg" },
  { slug: "resolucao-ana-42-2020", title: "Resolução ANA n. 42/2020 — Contratos de Programa", shortTitle: "Resolução ANA 42", description: "Norma de referência sobre celebração e execução de contratos de programa para prestação de serviços de saneamento básico.", type: "RESOLUCAO", number: "42/2020", issuingBody: "ANA", documentUrl: "https://www.gov.br/ana", publishedAt: new Date("2020-09-15"), legCategorySlug: "saneamento-leg" },

  // ── Recursos Hídricos ────────────────────────────────────────────────────
  { slug: "lei-9433-1997", title: "Lei n. 9.433/1997 — Política Nacional de Recursos Hídricos", shortTitle: "Lei das Águas", description: "Institui a Política Nacional de Recursos Hídricos e cria o Sistema Nacional de Gerenciamento de Recursos Hídricos. Estabelece a água como bem público, recurso limitado e dotado de valor econômico. Define outorga, cobrança e planos de bacia hidrográfica.", type: "LEI", number: "9.433/1997", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/leis/l9433.htm", publishedAt: new Date("1997-01-08"), effectiveAt: new Date("1997-01-08"), legCategorySlug: "recursos-hidricos" },
  { slug: "lei-9984-2000", title: "Lei n. 9.984/2000 — Criação da ANA", shortTitle: "Lei de Criação da ANA", description: "Cria a Agência Nacional de Águas e Saneamento Básico (ANA), entidade federal responsável pela implementação da Política Nacional de Recursos Hídricos, regulação do uso da água em rios federais e regulação de referência do saneamento.", type: "LEI", number: "9.984/2000", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/leis/l9984.htm", publishedAt: new Date("2000-07-17"), effectiveAt: new Date("2000-07-17"), legCategorySlug: "recursos-hidricos" },
  { slug: "resolucao-cnrh-16-2001", title: "Resolução CNRH n. 16/2001 — Outorga de Recursos Hídricos", shortTitle: "Resolução CNRH 16", description: "Estabelece critérios gerais para a outorga de direito de uso de recursos hídricos, regulamentando condições de prioridade de uso, vazões de referência e prazos de validade das outorgas.", type: "RESOLUCAO", number: "16/2001", issuingBody: "CNRH", documentUrl: "https://www.mma.gov.br/port/conama/legislacao/resolucoes-cnrh.html", publishedAt: new Date("2001-05-08"), legCategorySlug: "recursos-hidricos" },
  { slug: "resolucao-cnrh-65-2006", title: "Resolução CNRH n. 65/2006 — Outorga Preventiva", shortTitle: "Resolução CNRH 65", description: "Regulamenta a outorga preventiva de direito de uso de recursos hídricos para garantia a futuros usuários, permitindo reserva de disponibilidade hídrica para planejamento de projetos.", type: "RESOLUCAO", number: "65/2006", issuingBody: "CNRH", documentUrl: "https://www.mma.gov.br/port/conama/legislacao/resolucoes-cnrh.html", publishedAt: new Date("2006-12-07"), legCategorySlug: "recursos-hidricos" },

  // ── Meio Ambiente ────────────────────────────────────────────────────────
  { slug: "lei-6938-1981", title: "Lei n. 6.938/1981 — Política Nacional do Meio Ambiente", shortTitle: "PNMA", description: "Institui a Política Nacional do Meio Ambiente, seus fins e mecanismos de formulação e aplicação. Estabelece o Sistema Nacional do Meio Ambiente (SISNAMA), o Conselho Nacional do Meio Ambiente (CONAMA) e o licenciamento ambiental.", type: "LEI", number: "6.938/1981", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/leis/l6938.htm", publishedAt: new Date("1981-08-31"), effectiveAt: new Date("1981-09-02"), legCategorySlug: "meio-ambiente-leg" },
  { slug: "lei-9605-1998", title: "Lei n. 9.605/1998 — Lei de Crimes Ambientais", shortTitle: "Lei de Crimes Ambientais", description: "Dispõe sobre as sanções penais e administrativas derivadas de condutas e atividades lesivas ao meio ambiente. Inclui crimes de poluição de corpos hídricos, lançamento irregular de efluentes e danos à flora e fauna.", type: "LEI", number: "9.605/1998", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/leis/l9605.htm", publishedAt: new Date("1998-02-12"), effectiveAt: new Date("1998-02-12"), legCategorySlug: "meio-ambiente-leg" },
  { slug: "lei-12305-2010", title: "Lei n. 12.305/2010 — Política Nacional de Resíduos Sólidos", shortTitle: "PNRS", description: "Institui a Política Nacional de Resíduos Sólidos, com diretrizes para gestão integrada de resíduos. Define responsabilidade compartilhada, logística reversa e metas para eliminação de lixões. Diretamente ligada ao saneamento ambiental.", type: "LEI", number: "12.305/2010", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2010/lei/l12305.htm", publishedAt: new Date("2010-08-02"), effectiveAt: new Date("2010-08-02"), legCategorySlug: "meio-ambiente-leg" },
  { slug: "resolucao-conama-357-2005", title: "Resolução CONAMA n. 357/2005 — Classificação de Corpos d'Água", shortTitle: "CONAMA 357/2005", description: "Dispõe sobre a classificação dos corpos de água e diretrizes ambientais para o seu enquadramento, bem como as condições e padrões de lançamento de efluentes. Fundamental para projetos de ETEs e abastecimento.", type: "RESOLUCAO", number: "357/2005", issuingBody: "CONAMA", documentUrl: "https://www.ibama.gov.br/sophia/cnia/legislacao/MMA/RE0357-170305.PDF", publishedAt: new Date("2005-03-17"), legCategorySlug: "meio-ambiente-leg" },
  { slug: "resolucao-conama-430-2011", title: "Resolução CONAMA n. 430/2011 — Padrões de Lançamento de Efluentes", shortTitle: "CONAMA 430/2011", description: "Complementa e altera a Resolução 357/2005. Dispõe sobre condições e padrões de lançamento de efluentes no meio ambiente, incluindo padrões mínimos de qualidade para efluentes de ETEs de qualquer porte.", type: "RESOLUCAO", number: "430/2011", issuingBody: "CONAMA", documentUrl: "https://www.ibama.gov.br/sophia/cnia/legislacao/MMA/RE0430-130511.pdf", publishedAt: new Date("2011-05-13"), legCategorySlug: "meio-ambiente-leg" },

  // ── Saúde Pública ────────────────────────────────────────────────────────
  { slug: "portaria-gm-ms-888-2021", title: "Portaria GM/MS n. 888/2021 — Potabilidade da Água", shortTitle: "Portaria 888/2021 — Potabilidade", description: "Altera o Anexo XX da Portaria de Consolidação GM/MS n. 5/2017 para dispor sobre os procedimentos de controle e vigilância da qualidade da água para consumo humano e seu padrão de potabilidade.", type: "PORTARIA", number: "888/2021", issuingBody: "Ministério da Saúde", documentUrl: "https://bvsms.saude.gov.br/bvs/saudelegis/gm/2021/prt0888_04_05_2021.html", publishedAt: new Date("2021-05-04"), effectiveAt: new Date("2021-05-04"), legCategorySlug: "saude-publica" },

  // ── Infraestrutura e Concessões ──────────────────────────────────────────
  { slug: "lei-8987-1995", title: "Lei n. 8.987/1995 — Concessões e Permissões", shortTitle: "Lei de Concessões 8.987", description: "Dispõe sobre o regime de concessão e permissão da prestação de serviços públicos. Base legal para concessões de saneamento, definindo licitação obrigatória, direitos e obrigações do concessionário, revisão tarifária e extinção da concessão.", type: "LEI", number: "8.987/1995", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/leis/l8987cons.htm", publishedAt: new Date("1995-02-13"), effectiveAt: new Date("1995-02-13"), legCategorySlug: "infraestrutura-concessoes" },
  { slug: "lei-11079-2004", title: "Lei n. 11.079/2004 — Parcerias Público-Privadas (PPP)", shortTitle: "Lei de PPP", description: "Institui normas gerais para licitação e contratação de parceria público-privada no âmbito da administração pública. Modalidades: concessão patrocinada e concessão administrativa. Amplamente utilizada em projetos de saneamento.", type: "LEI", number: "11.079/2004", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2004/lei/l11079.htm", publishedAt: new Date("2004-12-30"), effectiveAt: new Date("2004-12-30"), legCategorySlug: "infraestrutura-concessoes" },
  { slug: "lei-11107-2005", title: "Lei n. 11.107/2005 — Consórcios Públicos", shortTitle: "Lei de Consórcios Públicos", description: "Dispõe sobre normas gerais de contratação de consórcios públicos entre entes federativos. Instrumento essencial para a regionalização do saneamento básico, permitindo que municípios se consorciem para prestação conjunta dos serviços.", type: "LEI", number: "11.107/2005", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2005/lei/l11107.htm", publishedAt: new Date("2005-04-06"), effectiveAt: new Date("2005-04-06"), legCategorySlug: "infraestrutura-concessoes" },
  { slug: "decreto-6017-2007", title: "Decreto n. 6.017/2007 — Regulamento dos Consórcios Públicos", shortTitle: "Decreto 6.017/2007", description: "Regulamenta a Lei 11.107/2005, estabelecendo normas para a execução da Lei de Consórcios Públicos, incluindo protocolo de intenções, estatutos, contratos de rateio e contratos de programa.", type: "DECRETO", number: "6.017/2007", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2007/decreto/d6017.htm", publishedAt: new Date("2007-01-17"), effectiveAt: new Date("2007-01-17"), legCategorySlug: "infraestrutura-concessoes" },
  { slug: "lei-13529-2017", title: "Lei n. 13.529/2017 — Fundos de Apoio à Estruturação", shortTitle: "Lei 13.529/2017", description: "Autoriza a União a participar de fundo de apoio à estruturação e ao desenvolvimento de projetos de concessões e parcerias público-privadas, viabilizando estudos técnicos para projetos de infraestrutura de saneamento.", type: "LEI", number: "13.529/2017", issuingBody: "Presidência da República", documentUrl: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2017/lei/L13529.htm", publishedAt: new Date("2017-12-04"), effectiveAt: new Date("2017-12-04"), legCategorySlug: "infraestrutura-concessoes" },

  // ── Normas Técnicas ABNT ─────────────────────────────────────────────────
  { slug: "nbr-7229-1993", title: "NBR 7229/1993 — Sistemas de Tanques Sépticos", shortTitle: "NBR 7229", description: "Especifica condições exigíveis para projeto, construção e operação de sistemas de tanques sépticos para tratamento de esgoto sanitário em edificações, indispensável para projetos de saneamento em áreas sem rede pública.", type: "NBR", number: "7229/1993", issuingBody: "ABNT", documentUrl: "https://www.abntcatalogo.com.br/norma.aspx?ID=4536", publishedAt: new Date("1993-09-30"), legCategorySlug: "normas-tecnicas" },
  { slug: "nbr-9648-1986", title: "NBR 9648/1986 — Redes Coletoras de Esgoto Sanitário", shortTitle: "NBR 9648", description: "Define terminologia aplicável ao estudo, concepção e projeto de sistemas de esgotos sanitários, essencial para projetos de engenharia de coleta e transporte de esgoto.", type: "NBR", number: "9648/1986", issuingBody: "ABNT", documentUrl: "https://www.abntcatalogo.com.br", publishedAt: new Date("1986-05-30"), legCategorySlug: "normas-tecnicas" },
  { slug: "nbr-12218-1994", title: "NBR 12.218/1994 — Rede de Distribuição de Água", shortTitle: "NBR 12.218", description: "Fixa condições exigíveis para elaboração de projeto de rede de distribuição de água para abastecimento público, incluindo dimensionamento hidráulico, materiais e pressões de serviço.", type: "NBR", number: "12.218/1994", issuingBody: "ABNT", documentUrl: "https://www.abntcatalogo.com.br", publishedAt: new Date("1994-06-30"), legCategorySlug: "normas-tecnicas" },
];

export const regulatoryAgencies = [
  { name: "ANA", fullName: "Agência Nacional de Águas e Saneamento Básico", slug: "ana", region: "NACIONAL", websiteUrl: "https://www.gov.br/ana", description: "Agência federal responsável pela regulação do uso de recursos hídricos e regulação de referência do saneamento básico." },
  { name: "ARSESP", fullName: "Agência Reguladora de Serviços Públicos do Estado de São Paulo", slug: "arsesp", region: "SUDESTE", uf: "SP", websiteUrl: "https://www.arsesp.sp.gov.br" },
  { name: "AGENERSA", fullName: "Agência Reguladora de Energia e Saneamento Básico do RJ", slug: "agenersa", region: "SUDESTE", uf: "RJ", websiteUrl: "https://www.agenersa.rj.gov.br" },
  { name: "ARSAE", fullName: "Agência Reguladora de Serviços de Abastecimento de Água e Esgotamento Sanitário de MG", slug: "arsae", region: "SUDESTE", uf: "MG", websiteUrl: "https://www.arsae.mg.gov.br" },
  { name: "ARSI", fullName: "Agência Reguladora de Saneamento e Infraestrutura do ES", slug: "arsi", region: "SUDESTE", uf: "ES", websiteUrl: "https://arsi.es.gov.br" },
  { name: "AGEPAR", fullName: "Agência Reguladora de Serviços Públicos Delegados do Paraná", slug: "agepar", region: "SUL", uf: "PR", websiteUrl: "https://www.agepar.pr.gov.br" },
  { name: "AGERGS", fullName: "Agência Estadual de Regulação dos Serviços Públicos Delegados do RS", slug: "agergs", region: "SUL", uf: "RS", websiteUrl: "https://www.agergs.rs.gov.br" },
  { name: "ARESC", fullName: "Agência de Regulação de Serviços Públicos de Santa Catarina", slug: "aresc", region: "SUL", uf: "SC", websiteUrl: "https://www.aresc.sc.gov.br" },
  { name: "ARCE", fullName: "Agência Reguladora de Serviços Públicos Delegados do Ceará", slug: "arce", region: "NORDESTE", uf: "CE", websiteUrl: "https://www.arce.ce.gov.br" },
  { name: "ARSAL", fullName: "Agência Reguladora de Serviços Públicos de Alagoas", slug: "arsal", region: "NORDESTE", uf: "AL", websiteUrl: "https://www.arsal.al.gov.br" },
  { name: "AGESPI", fullName: "Agência de Regulação dos Serviços Públicos Delegados do Piauí", slug: "agespi", region: "NORDESTE", uf: "PI", websiteUrl: "https://www.agespi.pi.gov.br" },
  { name: "ATR", fullName: "Agência Tocantinense de Regulação", slug: "atr", region: "NORDESTE", uf: "TO", websiteUrl: "https://www.atr.to.gov.br" },
  { name: "ADASA", fullName: "Agência Reguladora de Águas, Energia e Saneamento do DF", slug: "adasa", region: "CENTRO_OESTE", uf: "DF", websiteUrl: "https://www.adasa.df.gov.br" },
  { name: "AGR", fullName: "Agência Goiana de Regulação", slug: "agr", region: "CENTRO_OESTE", uf: "GO", websiteUrl: "https://www.agr.go.gov.br" },
  { name: "AGER", fullName: "Agência Estadual de Regulação dos Serviços Públicos Delegados de MT", slug: "ager", region: "CENTRO_OESTE", uf: "MT", websiteUrl: "https://www.ager.mt.gov.br" },
  { name: "AGEMS", fullName: "Agência Estadual de Regulação de Serviços Públicos de MS", slug: "agems", region: "CENTRO_OESTE", uf: "MS", websiteUrl: "https://www.agems.ms.gov.br" },
  { name: "AGEAC", fullName: "Agência Reguladora dos Serviços Públicos do Acre", slug: "ageac", region: "NORTE", uf: "AC", websiteUrl: "https://www.ageac.ac.gov.br" },
  { name: "ARCON", fullName: "Agência de Regulação e Controle de Serviços Públicos do Pará", slug: "arcon", region: "NORTE", uf: "PA", websiteUrl: "https://www.arcon.pa.gov.br" },
  { name: "ARSEP", fullName: "Agência Reguladora de Serviços Públicos do Rio Grande do Norte", slug: "arsep-rn", region: "NORTE", uf: "RN", websiteUrl: "https://www.arsep.rn.gov.br" },
  { name: "ARES-PCJ", fullName: "Agência Reguladora dos Serviços de Saneamento das Bacias PCJ", slug: "ares-pcj", region: "INTERMUNICIPAL", websiteUrl: "https://www.arespcj.com.br", description: "Regula centenas de municípios nas bacias dos rios Piracicaba, Capivari e Jundiaí." },
  { name: "ARIS-SC", fullName: "Agência Reguladora Intermunicipal de Saneamento de SC", slug: "aris-sc", region: "INTERMUNICIPAL", websiteUrl: "https://www.aris.sc.gov.br", description: "Agência intermunicipal que regula serviços de saneamento em Santa Catarina." },
];
